version: "3.8"

services:
  yt-mp3-bot:
    build: .
    container_name: yt-mp3-bot
    env_file:
      - .env
    volumes:
      - ./downloads:/tmp/ytmusicbot
      - redis-sock:/var/run/redis
    restart: unless-stopped
    network_mode: "service:vpn"
    depends_on:
      - redis

  redis:
    image: redis
    container_name: yt-mp3-redis
    restart: unless-stopped
    volumes:
      - redis-sock:/var/run/redis
    command: >
      sh -c "mkdir -p /var/run/redis && chown redis:redis /var/run/redis &&
             redis-server --unixsocket /var/run/redis/redis.sock --unixsocketperm 770"
  vpn:
    image: qmcgaw/gluetun
    container_name: pia-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8888:8888 # optional proxy/test port
    volumes:
      - ./gluetun:/gluetun
    env_file:
      - .env
    restart: unless-stopped

volumes:
  redis-sock: