version: "3.8"

services:
  yt-mp3-bot:
    build: .
    container_name: yt-mp3-bot
    env_file:
      - .env
    volumes:
      - ./downloads:/tmp/ytmusicbot
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis
    container_name: yt-mp3-redis
    restart: unless-stopped
    ports:
      - "6379:6379"