name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Deploy over SSH
      run: |
        ssh root@${{ secrets.SERVER_HOST }} << 'EOF'
          echo "--- Connected ---"
          cd /root/yt-music-to-tg
          git pull
          docker compose down
          docker compose up -d --build --force-recreate --no-deps --remove-orphans 
          docker image prune -af
        EOF